### ISSUE TITLE
Alter deployment script to sync master & develop

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/docs.vanillaframework.io#74]

**Comment by yaili** [comment]
@barrymcgee are you working on this? Has no assignee but is "In progress"…

**Comment by barrymcgee** [comment]
@yaili Yes - now assigned..

**Comment by yaili** [comment]
@barrymcgee gracias

**Comment by barrymcgee** [comment]
@nottrobin I've amended the script here, can you review:

https://gist.github.com/barrymcgee/382058dc7c61994afcd0b24fcaab8c62#file-jenkins-sh-L16

Changes:
- Amended line 16/17 to initially check out develop instead of master
- Added lines 63-70 to merge develop into master

**Comment by nottrobin** [comment]
That block says "git clone *or* git checkout". You'll need to also add "--branch develop" to the "git clone" part.

Don't we also want the script to automatically update master from develop, and then update master? Rather than just release from develop.

**Comment by barrymcgee** [comment]
@nottrobin I've updated with those changes

**Comment by nottrobin** [comment]
I've run through this and tested it out. Basically it works great.

I've [made a few tweaks](https://gist.github.com/nottrobin/d5be7304e0aa4f12e1231dad9e90c33f), (mostly unrelated improvements on how it was working before):

- Change `set -ex` to `set -e` so we don't get quite so much confusing console output in Jenkins
- Removed duplicate "Get new version number and update package.json" section
- Moved the "Check the version doesn't exist" tag check to much nearer the top (fail early)
- Added more status reporting messages, tweaked the formatting slightly
- Push package.json change back up to `develop` branch, rather than `master`
- Add the version tag when on `master`, rather than `develop`
- Push back up to `master` after a merge `develop` in
- Make pushing to assets server the very final task

If you're happy with how this looks, feel free to update the jenkins job. I'm happy with it.

**Comment by barrymcgee** [comment]
@nottrobin Great, thanks - now updated on Jenkins.
