### ISSUE TITLE
Site needs hard refresh to display changes

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/docs.vanillaframework.io#79]
If I visit the site since the last time it's been updated, the site doesn't show the latest changes, only after a hard refresh. Most people wouldn't expect this to be needed and would be looking at out of date content.

I've also seen this happen on other people's laptops, not just mine.

**Comment by nottrobin** [comment]
Do you mean that the code snippets and the examples in the iframes don't update? Or that all the content on the page doesn't?

Because the former makes a lot of sense to me. I suspect that when the JavaScript makes requests to the examples site (e.g. <http://vanilla-framework.github.io/vanilla-framework/examples/base/code/>), the response it gets may well be from the browser's cache.

One way to fix this would be to update the way [example-js](https://github.com/ubuntudesign/example-js) requests those links. We could either have it append a random string to every request, so they're never cached (e.g. `http://vanilla-framework.github.io/vanilla-framework/examples/base/code/?a23fe`) or if the script was somehow aware of which version of vanilla-framework it was expecting, it could just update the cache-buster when the version changes.

@anthonydillon - thoughts?

**Comment by yaili** [comment]
I mean the whole site. For example, I typed the URL of the site to check if the navigation was in alphab. order and it wasn't, then I hard refreshed and it was updated.

This happens also with the content of pages (text, examples, etc.).

**Comment by anthonydillon** [comment]
This is going to take some investigation. Something obscure must be causing
this.

**Comment by barrymcgee** [comment]
Could this not be fixed by cache busting static assets by adding a commit hash to the end of the `.css` and `.js` file includes?

**Comment by nottrobin** [comment]
What Yaili describes suggests it's the whole page, as in the actual content, not just styling and JavaScript.

I am reasonably sure we *will* see issues with the example-js assets being cached, which should be fixed as I described above in example-js itself, but this seems much more serious.

**Comment by yaili** [comment]
I can't verify whether this is still happening? Shall we close for now?

**Comment by nottrobin** [comment]
@yaili I'm happy to if you are.
